name: Main pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: ensure compilation
        env:
          GOOS: linux
        run: go build

      - name: Test
        run: go test -v ./...
